// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllTimeChecks() {
  return window['go']['core']['App']['GetAllTimeChecks']();
}

export function GetAllTimeScans() {
  return window['go']['core']['App']['GetAllTimeScans']();
}

export function GetCtx() {
  return window['go']['core']['App']['GetCtx']();
}

export function GetJudge() {
  return window['go']['core']['App']['GetJudge']();
}

export function GetPoolSize() {
  return window['go']['core']['App']['GetPoolSize']();
}

export function GetTimeoutString() {
  return window['go']['core']['App']['GetTimeoutString']();
}

export function Refresh() {
  return window['go']['core']['App']['Refresh']();
}
