// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetAllTimeChecks():Promise<number>;

export function GetAllTimeScans():Promise<number>;

export function GetCtx():Promise<context.Context>;

export function GetJudge():Promise<string>;

export function GetPoolSize():Promise<number>;

export function GetTimeoutString():Promise<string>;

export function Refresh():Promise<string>;
