on: push
name: Linter

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint-rs:
    name: Rust linter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Run Clippy
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils
          cd ./src-tauri && cargo clippy
